# Generated by Django 3.1 on 2020-08-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='sname',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
