# Generated by Django 3.1 on 2020-08-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_details_sname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='sname',
            new_name='email',
        ),
    ]
